### ISSUE TITLE
Feature Request - Save.rvdata2

### ISSUE THREAD

**Issue by Makozapper** [SnowSzn/rgss-db-cli#2]
Hello! Would it be possible to add exporting/importing of .rvdata2 save files (for VX ACE)?

**Comment by SnowSzn** [comment]
> Hello! Would it be possible to add exporting/importing of .rvdata2 save files (for VX ACE)?

I could take a look, at first, I see two problems with supporting save files:

1. The directory where the save files are created can change depending on the game, unlike the database files, which are standardized to always be in the Data folder.
2. The format of the save file can change as well, so the rgss-db function that allows to select objects I don't think it will be supported.

To solve 1 at least, I think I could make any save file that is inside the Data folder to be detected by the application, so that the user would have to move the save file manually to this folder for it to be detected.

**Comment by Makozapper** [comment]
Thank you!

For 1, reading save files placed inside the Data folder makes perfect sense to me. For 2, would it work to simply transform the data contained in the save files in whatever structure it holds into text form?

**Comment by SnowSzn** [comment]
> Thank you!
> 
> For 1, reading save files placed inside the Data folder makes perfect sense to me. For 2, would it work to simply transform the data contained in the save files in whatever structure it holds into text form?

Yeah, a glob pattern like Save* inside the data folder could easily match against any save file with the proper extension [.rxdata, .rvdata, .rvdata2], already tested, and save files are detected successfully.

Still, the deserialization fails because of the special format of the savefile, I think I will have to re-structure the way I deserialize the files to support this behavior.

For example, a RPG Maker VX Ace savefile is formatted like this:
- header hash (a Hash instance that acts as a save file header)
- contents hash (a Hash instance that contains the actual data)

Both are serialized as-is, so I would need to change the behavior to process the data file until EOL is reached, which was not needed in the current version because the RPG Maker database serializes all data either in a single hash, a single array, and a single object (RPG::Map)

> For 2, would it work to simply transform the data contained in the save files in whatever structure it holds into text form?

Unless I'm wrong that wouldn't work, mainly because the data that exists within a save file are game objects like Game_System, Game_Map, etc... and these needs to be deserialized and re-created using a model of classes, which is the way rgss-db works, it loads a set of classes based on the detected RPG Maker version.

The thing is, these classes (Game_System, Game_Map, etc...) are subject to change depending on the game project or usage of community plugins.

I think I could look into supporting the base classes that come with a vanilla project as-is.
To support modifications I could add a new option to rgss-db ``--model "path/to/model/" `` to allow loading a custom model instead of the vanilla one in case the game classes were modified.

**Comment by SnowSzn** [comment]
I've changed the deserialization method (still need to test it), here's an example of a savefile deserialized:

```YAML
---
- :characters:
  - - Actor4
    - 0
  :playtime_s: '00:00:04'
- :system: !ruby/object:Game_System
    save_disabled: false
    menu_disabled: false
    encounter_disabled: false
    formation_disabled: false
    battle_count: 0
    save_count: 1
    version_id: 90109136
    window_tone:
    battle_bgm:
    battle_end_me:
    saved_bgm:
    frames_on_save: 266
    bgm_on_save: !ruby/object:RPG::BGM
      name: ''
      volume: 100
      pitch: 100
      pos: 297684
    bgs_on_save: !ruby/object:RPG::BGS
      name: ''
      volume: 100
      pitch: 100
      pos: 0
  :timer: !ruby/object:Game_Timer
    count: 0
    working: false
  :message: !ruby/object:Game_Message
    texts: []
    choices: []
    face_name: ''
    face_index: 0
    background: 0
    position: 2
    choice_cancel_type: 0
    choice_proc:
    num_input_variable_id: 0
    num_input_digits_max: 0
    item_choice_variable_id: 0
    scroll_mode: false
    scroll_speed: 2
    scroll_no_fast: false
    visible: false
  :switches: !ruby/object:Game_Switches
    data: []
  :variables: !ruby/object:Game_Variables
    data: []
  :self_switches: !ruby/object:Game_SelfSwitches
    data: {}
  :actors: !ruby/object:Game_Actors
    data:
    -
    - &1 !ruby/object:Game_Actor
      battler_name: ''
      battler_hue: 0
      actions: []
      speed: 0
      result: !ruby/object:Game_ActionResult
        battler: *1
        used: false
        missed: false
        evaded: false
        critical: false
        success: false
        hp_damage: 0
        mp_damage: 0
        tp_damage: 0
        hp_drain: 0
        mp_drain: 0
        added_states: []
        removed_states: []
        added_buffs: []
        added_debuffs: []
        removed_buffs: []
      last_target_index: 0
      guarding: false
      animation_id: 0
      animation_mirror: false
      sprite_effect_type:
      tp: 0
      mp: 41
      hp: 562
      hidden: false
      param_plus:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      states: []
      state_turns: {}
      state_steps: {}
      buffs:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      buff_turns: {}
      actor_id: 1
      name: Eric
      nickname: Muerte Plateada
      character_name: Actor4
      character_index: 0
      face_name: Actor4
      face_index: 0
      class_id: 1
      level: 1
      exp:
        1: 0
      equips:
      - !ruby/object:Game_BaseItem
        class: !ruby/class 'RPG::Weapon'
        item_id: 1
      - !ruby/object:Game_BaseItem
        class:
        item_id: 0
      - !ruby/object:Game_BaseItem
        class:
        item_id: 0
      - !ruby/object:Game_BaseItem
        class: !ruby/class 'RPG::Armor'
        item_id: 1
      - !ruby/object:Game_BaseItem
        class:
        item_id: 0
      skills: []
      action_input_index: 0
      last_skill: !ruby/object:Game_BaseItem
        class:
        item_id: 0
  :party: !ruby/object:Game_Party
    in_battle: false
    gold: 0
    steps: 4
    last_item: !ruby/object:Game_BaseItem
      class:
      item_id: 0
    menu_actor_id: 0
    target_actor_id: 0
    actors:
    - 1
    items: {}
    weapons: {}
    armors: {}
  :troop: !ruby/object:Game_Troop
    in_battle: false
    screen: !ruby/object:Game_Screen
      pictures: !ruby/object:Game_Pictures
        data: []
      brightness: 255
      fadeout_duration: 0
      fadein_duration: 0
      tone: !ruby/object:Tone
        red: 0.0
        green: 0.0
        blue: 0.0
        gray: 0.0
      tone_target: !ruby/object:Tone
        red: 0.0
        green: 0.0
        blue: 0.0
        gray: 0.0
      tone_duration: 0
      flash_color: !ruby/object:Color
        red: 0.0
        green: 0.0
        blue: 0.0
        alpha: 0.0
      flash_duration: 0
      shake_power: 0
      shake_speed: 0
      shake_duration: 0
      shake_direction: 1
      shake: 0
      weather_type: :none
      weather_power: 0
      weather_power_target: 0
      weather_duration: 0
    interpreter: !ruby/object:Game_Interpreter
      depth: 0
      map_id: 0
      event_id: 0
      list:
      index: 1
      branch: {}
    event_flags: {}
    enemies: []
    turn_count: 0
    names_count: {}
  :map: !ruby/object:Game_Map
    screen: !ruby/object:Game_Screen
      pictures: !ruby/object:Game_Pictures
        data: []
      brightness: 255
      fadeout_duration: 0
      fadein_duration: 0
      tone: !ruby/object:Tone
        red: 0.0
        green: 0.0
        blue: 0.0
        gray: 0.0
      tone_target: !ruby/object:Tone
        red: 0.0
        green: 0.0
        blue: 0.0
        gray: 0.0
      tone_duration: 0
      flash_color: !ruby/object:Color
        red: 0.0
        green: 0.0
        blue: 0.0
        alpha: 0.0
      flash_duration: 0
      shake_power: 0
      shake_speed: 0
      shake_duration: 0
      shake_direction: 1
      shake: 0
      weather_type: :none
      weather_power: 0
      weather_power_target: 0
      weather_duration: 0
    interpreter: !ruby/object:Game_Interpreter
      depth: 0
      map_id: 0
      event_id: 0
      list:
      index: 1
      branch: {}
    map_id: 1
    events: {}
    display_x: 0
    display_y: 0
    vehicles:
    - !ruby/object:Game_Vehicle
      id: 0
      x: 0
      y: 0
      real_x: 0
      real_y: 0
      tile_id: 0
      character_name: Vehicle
      character_index: 0
      move_speed: 4
      move_frequency: 6
      walk_anime: false
      step_anime: false
      direction_fix: false
      opacity: 255
      blend_type: 0
      direction: 4
      pattern: 1
      priority_type: 1
      through: false
      bush_depth: 0
      animation_id: 0
      balloon_id: 0
      transparent: false
      move_list: []
      next_movement: []
      over_event: 0
      damage_floor: 0
      steps: 0
      move_route_forcing: false
      original_direction: 2
      original_pattern: 1
      anime_count: 0
      stop_count: 137
      jump_count: 0
      jump_peak: 0
      locked: false
      prelock_direction: 0
      move_succeed: true
      move_route:
      move_route_index: 0
      original_move_route:
      original_move_route_index: 0
      wait_count: 0
      type: :boat
      altitude: 0
      driving: false
      walking_bgm:
      map_id: 0
    - !ruby/object:Game_Vehicle
      id: 0
      x: 0
      y: 0
      real_x: 0
      real_y: 0
      tile_id: 0
      character_name: Vehicle
      character_index: 1
      move_speed: 5
      move_frequency: 6
      walk_anime: false
      step_anime: false
      direction_fix: false
      opacity: 255
      blend_type: 0
      direction: 4
      pattern: 1
      priority_type: 1
      through: false
      bush_depth: 0
      animation_id: 0
      balloon_id: 0
      transparent: false
      move_list: []
      next_movement: []
      over_event: 0
      damage_floor: 0
      steps: 0
      move_route_forcing: false
      original_direction: 2
      original_pattern: 1
      anime_count: 0
      stop_count: 137
      jump_count: 0
      jump_peak: 0
      locked: false
      prelock_direction: 0
      move_succeed: true
      move_route:
      move_route_index: 0
      original_move_route:
      original_move_route_index: 0
      wait_count: 0
      type: :ship
      altitude: 0
      driving: false
      walking_bgm:
      map_id: 0
    - !ruby/object:Game_Vehicle
      id: 0
      x: 0
      y: 0
      real_x: 0
      real_y: 0
      tile_id: 0
      character_name: Vehicle
      character_index: 3
      move_speed: 6
      move_frequency: 6
      walk_anime: false
      step_anime: false
      direction_fix: false
      opacity: 255
      blend_type: 0
      direction: 4
      pattern: 1
      priority_type: 0
      through: false
      bush_depth: 0
      animation_id: 0
      balloon_id: 0
      transparent: false
      move_list: []
      next_movement: []
      over_event: 0
      damage_floor: 0
      steps: 0
      move_route_forcing: false
      original_direction: 2
      original_pattern: 1
      anime_count: 0
      stop_count: 137
      jump_count: 0
      jump_peak: 0
      locked: false
      prelock_direction: 0
      move_succeed: true
      move_route:
      move_route_index: 0
      original_move_route:
      original_move_route_index: 0
      wait_count: 0
      type: :airship
      altitude: 0
      driving: false
      walking_bgm:
      map_id: 0
    name_display: true
    map: !ruby/object:RPG::Map
      display_name: Nombre que se muestra
      tileset_id: 1
      width: 17
      height: 13
      scroll_type: 0
      specify_battleback: false
      autoplay_bgm: false
      bgm: !ruby/object:RPG::BGM
        name: Dungeon4
        volume: 100
        pitch: 100
      autoplay_bgs: false
      bgs: !ruby/object:RPG::BGS
        name: ''
        volume: 80
        pitch: 100
      disable_dashing: false
      encounter_list: []
      encounter_step: 10
      parallax_name: ''
      parallax_loop_x: false
      parallax_loop_y: false
      parallax_sx: 0
      parallax_sy: 0
      parallax_show: false
      note: ''
      data: !ruby/object:Table
        dim: 3
        x: 17
        y: 13
        z: 4
        data:
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2832
        - 2816
        - 2816
        - 2840
        - 2088
        - 2076
        - 2076
        - 2076
        - 2056
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2052
        - 2086
        - 2832
        - 2816
        - 2816
        - 2818
        - 2836
        - 2836
        - 2837
        - 2861
        - 2064
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2850
        - 2817
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2840
        - 2082
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2052
        - 2076
        - 2086
        - 2832
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2840
        - 2064
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2850
        - 2836
        - 2817
        - 2816
        - 2816
        - 2816
        - 2816
        - 2820
        - 2844
        - 2854
        - 2064
        - 2048
        - 2048
        - 2048
        - 2048
        - 2052
        - 2086
        - 2832
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2840
        - 2082
        - 2068
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2850
        - 2817
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2820
        - 2854
        - 2064
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2832
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2816
        - 2840
        - 2082
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2832
        - 2816
        - 2816
        - 2816
        - 2816
        - 2820
        - 2844
        - 2854
        - 2064
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2832
        - 2816
        - 2816
        - 2816
        - 2820
        - 2854
        - 2082
        - 2068
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2834
        - 2844
        - 2844
        - 2844
        - 2854
        - 2082
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2052
        - 2076
        - 2056
        - 2048
        - 2048
        - 2072
        - 2860
        - 2082
        - 2068
        - 2068
        - 2068
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2072
        - 2862
        - 2064
        - 2048
        - 2048
        - 2050
        - 2068
        - 2049
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2048
        - 2050
        - 2068
        - 2049
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2888
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2866
        - 2884
        - 2884
        - 2885
        - 2909
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2898
        - 2865
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2888
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2888
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2898
        - 2884
        - 2865
        - 2864
        - 2864
        - 2864
        - 2864
        - 2868
        - 2892
        - 2902
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2888
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2898
        - 2865
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2868
        - 2902
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2864
        - 2888
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2864
        - 2864
        - 2868
        - 2892
        - 2902
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2880
        - 2864
        - 2864
        - 2864
        - 2868
        - 2902
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2882
        - 2892
        - 2892
        - 2892
        - 2902
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2908
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 2910
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      events: {}
      battleback_floor_name: ''
      battleback_wall_name: ''
    tileset_id: 1
    common_events: []
    tile_events: []
    scroll_direction: 2
    scroll_rest: 0
    scroll_speed: 4
    parallax_name: ''
    parallax_loop_x: false
    parallax_loop_y: false
    parallax_sx: 0
    parallax_sy: 0
    parallax_x: 0
    parallax_y: 0
    battleback1_name:
    battleback2_name:
    need_refresh: false
  :player: &2 !ruby/object:Game_Player
    id: 0
    x: 7.0
    y: 0.0
    real_x: 7.0
    real_y: 0.0
    tile_id: 0
    character_name: Actor4
    character_index: 0
    move_speed: 4
    move_frequency: 6
    walk_anime: true
    step_anime: false
    direction_fix: false
    opacity: 255
    blend_type: 0
    direction: 8
    pattern: 1
    priority_type: 1
    through: false
    bush_depth: 0
    animation_id: 0
    balloon_id: 0
    transparent: false
    move_list: []
    next_movement:
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    over_event: 0
    damage_floor: 1
    steps: 32
    move_route_forcing: false
    original_direction: 2
    original_pattern: 1
    anime_count: 0
    stop_count: 24
    jump_count: 0
    jump_peak: 0
    locked: false
    prelock_direction: 0
    move_succeed: true
    move_route:
    move_route_index: 0
    original_move_route:
    original_move_route_index: 0
    wait_count: 0
    vehicle_type: :walk
    vehicle_getting_on: false
    vehicle_getting_off: false
    followers: !ruby/object:Game_Followers
      visible: true
      gathering: false
      data:
      - &3 !ruby/object:Game_Follower
        id: 0
        x: 7.0
        y: 0.875
        real_x: 7.0
        real_y: 0.875
        tile_id: 0
        character_name: ''
        character_index: 0
        move_speed: 4
        move_frequency: 6
        walk_anime: true
        step_anime: false
        direction_fix: false
        opacity: 255
        blend_type: 0
        direction: 8
        pattern: 1
        priority_type: 1
        through: true
        bush_depth: 0
        animation_id: 0
        balloon_id: 0
        transparent: false
        move_list: []
        next_movement:
        - 4
        - 4
        - 4
        - 4
        - 4
        - 8
        - 8
        over_event: 0
        damage_floor: 0
        steps: 0
        move_route_forcing: false
        original_direction: 2
        original_pattern: 1
        anime_count: 0
        stop_count: 42
        jump_count: 0
        jump_peak: 0
        locked: false
        prelock_direction: 0
        move_succeed: true
        move_route:
        move_route_index: 0
        original_move_route:
        original_move_route_index: 0
        wait_count: 0
        member_index: 1
        preceding_character: *2
        move_value:
          :d:
          - 8
          :turn: true
        diagonal_move: false
        moved: false
      - &4 !ruby/object:Game_Follower
        id: 0
        x: 7.625
        y: 1.125
        real_x: 7.625
        real_y: 1.125
        tile_id: 0
        character_name: ''
        character_index: 0
        move_speed: 4
        move_frequency: 6
        walk_anime: true
        step_anime: false
        direction_fix: false
        opacity: 255
        blend_type: 0
        direction: 4
        pattern: 1
        priority_type: 1
        through: true
        bush_depth: 0
        animation_id: 0
        balloon_id: 0
        transparent: false
        move_list: []
        next_movement:
        - 8
        - 8
        - 8
        - 8
        - 4
        - 4
        - 4
        over_event: 0
        damage_floor: 0
        steps: 0
        move_route_forcing: false
        original_direction: 2
        original_pattern: 1
        anime_count: 0
        stop_count: 41
        jump_count: 0
        jump_peak: 0
        locked: false
        prelock_direction: 0
        move_succeed: true
        move_route:
        move_route_index: 0
        original_move_route:
        original_move_route_index: 0
        wait_count: 0
        member_index: 2
        preceding_character: *3
        move_value:
          :d:
          - 4
          :turn: true
        diagonal_move: false
        moved: false
      - !ruby/object:Game_Follower
        id: 0
        x: 8
        y: 1.625
        real_x: 8
        real_y: 1.625
        tile_id: 0
        character_name: ''
        character_index: 0
        move_speed: 4
        move_frequency: 6
        walk_anime: true
        step_anime: false
        direction_fix: false
        opacity: 255
        blend_type: 0
        direction: 8
        pattern: 1
        priority_type: 1
        through: true
        bush_depth: 0
        animation_id: 0
        balloon_id: 0
        transparent: false
        move_list: []
        next_movement:
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        - 8
        over_event: 0
        damage_floor: 0
        steps: 0
        move_route_forcing: false
        original_direction: 2
        original_pattern: 1
        anime_count: 0
        stop_count: 40
        jump_count: 0
        jump_peak: 0
        locked: false
        prelock_direction: 0
        move_succeed: true
        move_route:
        move_route_index: 0
        original_move_route:
        original_move_route_index: 0
        wait_count: 0
        member_index: 3
        preceding_character: *4
        move_value:
          :d:
          - 8
          :turn: true
        diagonal_move: false
        moved: false
    transferring: false
    new_map_id: 0
    new_x: 0
    new_y: 0
    new_direction: 0
    encounter_count: 4
    move_value:
      :d:
      - 8
      :turn: true
    diagonal_move: false
    moved: false
```

Is this what you are looking for?
