### ISSUE TITLE
Events disappear from maps

### ISSUE THREAD

**Issue by fortnumxy** [SnowSzn/rgss-db-cli#3]
I've been able to export all of my data fine and the resultant json looks great. Unfortunately when I import map data back into rvdata2 then the events disappear from the VX ACE editing window.

Steps to reproduce:

1) create a new VX Ace project.
2) create a new event in the editor, I create mine just to the left of the player character so that I know where it is and also assign a graphic.
3) save and close VX ACE
4) export the database using rgss-db to json, I export all files.
5) import all of the files
6) load VX ACE, the events are no longer showing in the editor.

NOTES: 
 - I've tried this with multiple projects now (in case my inital project was too big or something). 
 - When I say the events are not showing in the editor I don't just mean the graphic, there is no darkened square to indicate an event and right clicking the square only offers creation of a new event, not editing of the existing event.
 - After loading in an imported map, any new event I create does not show on the map.
 - If you try the game, the events are still there! They're just misssing from the VX Ace editor.
 - I at first tried modifying the json, but upon assuming I made a mistake, the test above does no modification of the exported JSON, it's a straight export then import.

**Comment by SnowSzn** [comment]
Hi @fortnumxy 

Thanks for reporting it!

After following your steps, I can confirm events disappear from the map in the editor, not only in RPG Maker VX Ace but in RPG Maker VX and RPG Maker XP too.

First thing first, Since you said you tried it in your initial project, I hope you did not lose any progress using rgss-db!
You can recover the original map by going into the back ups folder that the tool creates automatically, you could copy-paste the back up created prior the import operation and recover your events

I am currently testing and **I discovered that with YAML it works as it should**, I think I figured out why you lose events when importing from JSON, here is why:

Take a look at the same Map data file in JSON and YAML, specifically, the events hash:

JSON
```json
  "events": {
    "1": {
      "json_class": "RPG::Event",
      "pages": [
        {
          "json_class": "RPG::Event::Page",
          "move_type": 0,
          "list": [
            {
              "json_class": "RPG::EventCommand",
              "parameters": [
                "Hello World!"
              ],
              "indent": 0,
              "code": 101
            },
            {
              "json_class": "RPG::EventCommand",
              "parameters": [

              ],
              "indent": 0,
              "code": 0
            }
          ],
          "condition": {
            "json_class": "RPG::Event::Page::Condition",
            "switch2_valid": false,
            "self_switch_ch": "A",
            "switch1_id": 1,
            "switch1_valid": false,
            "variable_value": 0,
            "self_switch_valid": false,
            "variable_id": 1,
            "variable_valid": false,
            "switch2_id": 1
          },
          "direction_fix": false,
          "move_route": {
            "json_class": "RPG::MoveRoute",
            "list": [
              {
                "json_class": "RPG::MoveCommand",
                "parameters": [

                ],
                "code": 0
              }
            ],
            "skippable": false,
            "repeat": true
          },
          "trigger": 0,
          "step_anime": false,
          "move_frequency": 3,
          "graphic": {
            "json_class": "RPG::Event::Page::Graphic",
            "opacity": 255,
            "character_name": "006-Fighter06",
            "pattern": 2,
            "tile_id": 0,
            "direction": 4,
            "blend_type": 0,
            "character_hue": 0
          },
          "always_on_top": false,
          "walk_anime": true,
          "move_speed": 3,
          "through": false
        }
      ],
      "name": "EV001",
      "y": 5,
      "x": 8,
      "id": 1
    }
  },
```

YAML
```yaml
events:
  1: !ruby/object:RPG::Event
    pages:
    - !ruby/object:RPG::Event::Page
      move_type: 0
      list:
      - !ruby/object:RPG::EventCommand
        parameters:
        - Hello World!
        indent: 0
        code: 101
      - !ruby/object:RPG::EventCommand
        parameters: []
        indent: 0
        code: 0
      condition: !ruby/object:RPG::Event::Page::Condition
        switch2_valid: false
        self_switch_ch: A
        switch1_id: 1
        switch1_valid: false
        variable_value: 0
        self_switch_valid: false
        variable_id: 1
        variable_valid: false
        switch2_id: 1
      direction_fix: false
      move_route: !ruby/object:RPG::MoveRoute
        list:
        - !ruby/object:RPG::MoveCommand
          parameters: []
          code: 0
        skippable: false
        repeat: true
      trigger: 0
      step_anime: false
      move_frequency: 3
      graphic: !ruby/object:RPG::Event::Page::Graphic
        opacity: 255
        character_name: 006-Fighter06
        pattern: 2
        tile_id: 0
        direction: 4
        blend_type: 0
        character_hue: 0
      always_on_top: false
      walk_anime: true
      move_speed: 3
      through: false
    name: EV001
    y: 5
    x: 8
    id: 1
```

There is a difference between both events hash, **the hash keys**.

When Map data files are saved into JSON, the events hash is saved with its keys as Strings, this is a limitation because JSON only support keys that are Strings, so when the JSON file is imported back into the binary format (rvdata2, rvdata or rxdata) the key for each event is saved as String instead of as Integer.

That explains why RPG Maker editor fails to show the events on the editor but when running the game they show on the map, the editor has no idea how to treat this hash because the keys are not supposed to be strings.

I will work on fixing it ASAP and push a new update.
